### PR TITLE
PostHog integration

### PR DESCRIPTION
**Pull request by kappa90**
This PR introduces a new integration with [Posthog](https://posthog.com), the self-hosted analytics tool.

The goal of the integration is to capture flag events inside of Posthog.

### Availability
I am helping Posthog developing integrations and they asked me to provide one for LaunchDarkly. This integration is intended for all LaunchDarkly's customers.

### Testing the integration
I included a README to test the integration.

This is a preview from the integration validation run:

```
URL:    $ENDPOINTURL/capture
METHOD: POST
HEADER: Content-Type: application/json
BODY:   targeting-rule-update.json
{
  "api_key": "$APIKEY",
  "event": "Demo flag",
  "properties": {
    "launchDarklyEventId": "5e38c0d506121d8aaf15392b",
    "launchDarklyEventAccountId": "569f514156e003339cfd3917",
    "launchDarklyEventType": "flag",
    "comment": "Adjusting the targeting rules",
    "distinct_id": "569f514183f2164430000002",
    "email": "testing@launchdarkly.com",
    "firstName": "Henrietta",
    "lastName": "Powell",
    "title": "Henrietta Powell updated the flag Demo flag in &#x27;Production&#x27;"
  },
  "timestamp": "2020-02-04T00:54:45Z"
}
```

Where `$ENDPOINTURL` and `$APIKEY` are Posthog instance's URL and API key.

Important: The timestamp that comes from the validation run is very old (2020), so the event might not be immediately apparent in Posthog's Live Events view, since the time window is probably going to be smaller than two years. I recommend changing to timestamp to the current datetime.

### Documentation
I created a [PR in the LaunchDarkly docs](https://github.com/launchdarkly/LaunchDarkly-Docs/pull/254) for a User manual, and I included a README in this PR as well.

Let me know if there are any questions, thank you!

### CODE REVIEW

**Comment by InTheCloudDan** [comment]
@kappa90 thank you for submitting the PR! Could you please fill out the form under `Become a Partner` at https://launchdarkly.com/partners/ so we can get that process started and work towards getting this merged?

**Comment by InTheCloudDan** [comment]
@kappa90 per our call the suggested change for name I had was to convert it to `verbKind` https://github.com/launchdarkly/integration-framework/blob/ed2c83e59e4bee8628715eb2ba5ace2364bfc70a/sample-context/flag/toggle.json#L86 another option is that if the format is free-form on your side it may just be worth adding that and keeping the `name` as is.

**Comment by kappa90** [comment]
> @kappa90 per our call the suggested change for name I had was to convert it to `verbKind`
> 
> https://github.com/launchdarkly/integration-framework/blob/ed2c83e59e4bee8628715eb2ba5ace2364bfc70a/sample-context/flag/toggle.json#L86
> 
> another option is that if the format is free-form on your side it may just be worth adding that and keeping the `name` as is.

Done, we should be good to go!

**Review by ldhenry — CHANGES_REQUESTED** [review]
This looks great. My only remaining suggestion is to remove the `yarn.lock` file.

**Review by ldhenry — COMMENTED** [review]
The code Looks great to me. We'll just need to get approval from our partner team before moving forward. We'll let you know if we need any additional information or changes.

Thanks,
Henry

**Review by ldhenry — APPROVED** [review]

**Pull request closed without merging**
